### ISSUE TITLE
Subscribers to cmd_vel not working when using teleop

### ISSUE THREAD

**Issue by thorstink** [ros2/teleop_twist_keyboard#16]
Hi; 
I tried using teleop_twist_keyboard that came with my crystal install. I also tried the latest version here on the crystal and master branch...

I can run it, and published twists and see through ```ros2 topic echo /cmd_vel``` that is publishes correctly. If I launch a simple node (the same as a minimal-subscriber example, e.g. [from here](https://github.com/ros2/examples/blob/master/rclcpp/minimal_subscriber/lambda.cpp) but use ```geometry::msg::Twist``` instead of ```std_msgs::String``` it does not work (the callback should print something to the console and it does not).

Checking with ```ros2 topic info /cmd_vel``` shows that there is a subscriber and a publisher, so it does seem something works...

However, if I manually publish something the ```cmd_vel``` using ```ros2 topic pub /cmd_vel geometry_msgs/Twist "{linear:  {x: 0.1, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}"``` the callback is triggered. ```ros2 topic info /cmd_vel``` then also shows there are two publishers active and one subscriber - which is correct.

So. I have little clue, but it seems like a bug. Or is there something I am missing?

Thanks for your time.

**Comment by clalancette** [comment]
It's a difference in QoS settings.  As it stands, [this line](https://github.com/ros2/teleop_twist_keyboard/blob/ros2/teleop_twist_keyboard.py#L121) sets up the publisher as best-effort, but the minimal subscriber example is using reliable QoS.  A best-effort publisher cannot publish to a reliable subscriber.

The minimal fix is to change this code to be a reliable publisher, which can publish to either reliable or best-effort subscriber.  A slightly more advanced fix would allow an option to be passed on the command-line to choose the QoS setting at runtime.

I probably won't have time to look at this in the near future, so if you'd like to submit a PR for this, that would be great.

**Comment by thorstink** [comment]
So changing the QoS to qos_profile_default works. I'll make a PR as it seems reasonable to me to use the default QoS.. I hope people do not use this particular teleop for special stuff.

**Comment by thorstink** [comment]
https://github.com/ros2/teleop_twist_keyboard/pull/18

That should "fix" it.
