### ISSUE TITLE
Crashes immediately on Windows

### ISSUE THREAD

**Issue by rotu** [ros2/teleop_twist_keyboard#20]
This package relies on the termios and tty python packages, which are not available on Windows.  When attempting to launch the node, I get an immediate error message:

> ```
> C:\Users\dan\Documents\ros2_ws>ros2 run teleop_twist_keyboard teleop_twist_keyboard
> Traceback (most recent call last):
>   File "C:\Users\dan\Documents\ros2_ws\install\teleop_twist_keyboard\lib\teleop_twist_keyboard\teleop_twist_keyboard-script.py", line 11, in <module>
>     load_entry_point('teleop-twist-keyboard', 'console_scripts', 'teleop_twist_keyboard')()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
>     return ep.load()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
>     return self.resolve()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "C:\Users\dan\Documents\ros2_ws\build\teleop_twist_keyboard\teleop_twist_keyboard.py", line 36, in <module>
>     import termios
> ModuleNotFoundError: No module named 'termios'
> ```

**Comment by clalancette** [comment]
Yeah, it's not super surprising.  This was originally written for ROS 1 Linux, and then we ported it to ROS 2.  So it likely needs work on Windows.

It's highly unlikely I'll have time to work on this, but if you could open a PR with changes needed for Windows I'd be happy to review it.

**Comment by clalancette** [comment]
This was fixed by #24, so closing.
