### ISSUE TITLE
Update README once teleop_twist_keyboard with #6 is re-packaged

### ISSUE THREAD

**Issue by clalancette** [ros2/teleop_twist_keyboard#7]
PR #5 changed the README.md to tell the user to use the fullpath for running teleop_twist_keyboard in beta2.  That was because of a bug, which is now fixed in #6 .  The next time that teleop_twist_keyboard is packaged, we should revert PR #5.

**Comment by dirk-thomas** [comment]
Reverting #5 is not the right fix (the instructions did contain a ROS 1 specific command before). Instead it should recommend `ros2 run teleop_twist_keyboard teleop_twist_keyboard` for all cases.

**Comment by mikaelarguedas** [comment]
#5 should not be reverted because we will end up with `rosrun teleop_twist_keyboard teleop_twist_keyboard.py` (a ROS1 invocation) and the previous formatting issues.

#8 should be merge instead of reverting #5
